version: '3'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - mysql
    networks:
      - app-network
    # backend service waits until MySQL port is open
    entrypoint: >
      sh -c "while ! nc -z mysql 3306; do
      echo 'Waiting for MySQL...'; sleep 3; done;
      npm start"

  client:
    build:
      context: ./client
    volumes:
      # mount src and public to enable hot reloading
      - ./client/src:/app/src
      - ./client/public:/app/public
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    container_name: inreach-mysql
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "3306:3306"
    volumes:
      - ./db/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
